export type Stage = 'Research' | 'Ideation' | 'Prototype' | 'Final Design';
export type Asset = { name: string; stage: Stage; size: string; type: string };
export const demoAssets: Asset[] = [
  { name: 'User Interview.pdf', stage: 'Research', size: '2.4 MB', type: 'PDF' },
  { name: 'Market Research.pdf', stage: 'Research', size: '3.1 MB', type: 'PDF' },
  { name: 'Competitor Analysis.pdf', stage: 'Research', size: '1.8 MB', type: 'PDF' },
  { name: 'Sketch 01.jpg', stage: 'Ideation', size: '4.2 MB', type: 'JPG' },
  { name: 'Sketch 02.jpg', stage: 'Ideation', size: '3.7 MB', type: 'JPG' },
  { name: 'Wireframe.fig', stage: 'Prototype', size: '8.2 MB', type: 'FIG' },
  { name: 'Prototype.fig', stage: 'Prototype', size: '12.5 MB', type: 'FIG' },
  { name: 'Final Render 01.png', stage: 'Final Design', size: '5.6 MB', type: 'PNG' },
  { name: 'Final Render 02.png', stage: 'Final Design', size: '4.8 MB', type: 'PNG' },
];
export const dimensions = [
  { name: 'Research', score: 82, evidence: 'Interview notes and a competitor review establish the context.', next: 'Connect each key finding to a design decision.' },
  { name: 'Problem Definition', score: 76, evidence: 'The brief describes cooking friction, but the target scenario is broad.', next: 'Focus the problem statement on one recurring kitchen task.' },
  { name: 'Product Thinking', score: 91, evidence: 'The prototype combines guided cooking, timers, and hands-free control.', next: 'Explain the trade-off behind choosing these three capabilities.' },
  { name: 'Ideation', score: 86, evidence: 'Two sketch directions explore the form and countertop footprint.', next: 'Show why the selected direction best addresses the brief.' },
  { name: 'Validation', score: 54, evidence: 'A prototype is present; no usability test evidence was found.', next: 'Run a task-based study and document observations.' },
  { name: 'Visual Design', score: 88, evidence: 'Final renders show a consistent product form and visual language.', next: 'Include a close-up that explains an interaction detail.' },
  { name: 'Storytelling', score: 68, evidence: 'The material follows activities rather than decisions and outcomes.', next: 'Restructure the case study around problem, insight, decision, and evidence.' },
];
export const careers = [
  { name: 'Product Designer', score: 86, label: 'Strongest fit', detected: 'Your materials connect user research, concept exploration, and a working prototype.', why: 'This provides evidence of thinking across the product lifecycle.', next: 'Add validation and make the reasoning behind each product decision visible.', skills: ['Product strategy', 'Concept development', 'Prototyping'] },
  { name: 'UX Designer', score: 82, label: 'Strong fit', detected: 'Interview notes, wireframes, and task flows show a user-centered process.', why: 'UX portfolios need a clear connection between user needs and interaction choices.', next: 'Test the recipe-selection flow and connect observations to an iteration.', skills: ['User research', 'Interaction design', 'User flows'] },
  { name: 'Industrial Designer', score: 79, label: 'Promising fit', detected: 'Your sketches and final renders explore a physical kitchen companion.', why: 'Form development is relevant, but manufacturing and ergonomic evidence is limited.', next: 'Add material rationale, dimensions, and a hands-on ergonomic check.', skills: ['Form exploration', '3D visualization', 'Physical prototyping'] },
  { name: 'UI Designer', score: 68, label: 'Developing fit', detected: 'The prototype includes interface screens, with limited component documentation.', why: 'UI roles look for interaction states, visual consistency, and reusable systems.', next: 'Add a component sheet, accessible color choices, and error states.', skills: ['Interface design', 'Visual hierarchy', 'Components'] },
];
export const gaps = [
  { id: 'validation', title: 'Missing usability testing', severity: 'High priority', stage: 'Validation', file: 'Prototype.fig', detected: 'An interactive cooking flow is present, but no test protocol, observations, or iterations were found in the uploaded materials.', why: 'A reviewer can see your solution, but cannot assess whether it works for the people you designed it for.', action: 'Test three core tasks with 3-5 participants. Record friction, completion, and the changes you make.', prompt: 'Help me plan a usability test', response: 'For Smart Kitchen Companion, test three tasks: find a recipe, start a hands-free timer, and recover from a missed instruction. Recruit 3-5 people who cook regularly. Ask them to think aloud; record completion, hesitation, and errors. Use a table with Task / Observation / Severity / Design change. This is a proposed test plan, not evidence that testing has happened.' },
  { id: 'evidence', title: 'Weak research-to-strategy evidence', severity: 'High priority', stage: 'Research', file: 'User Interview.pdf', detected: 'Interview themes and product features appear in separate documents, without an explicit trace between them.', why: 'Readers need to understand how research changed your decisions, rather than simply see that research happened.', action: 'Create an evidence map: interview observation, user need, design decision, and the remaining assumption.', prompt: 'Connect my findings to design decisions', response: 'Build a four-column evidence map for this project: Interview observation / User need / Product decision / What remains untested. For the hands-free interaction, insert an actual observation from User Interview.pdf before claiming that the feature addresses it. Label any proposed connection as a hypothesis until you verify the source.' },
  { id: 'story', title: 'Storytelling is too descriptive', severity: 'Needs attention', stage: 'Storytelling', file: 'Market Research.pdf', detected: 'The project describes activities and deliverables, with little emphasis on decisions or trade-offs.', why: 'A strong case study lets a reviewer follow your judgment and contribution, not just the sequence of tasks.', action: 'Reframe each section as a question, a decision, and the evidence that supports it.', prompt: 'Help me rewrite the project story', response: 'Try this structure for Smart Kitchen Companion: What makes cooking fragmented? / What did we learn? / Which interaction did we prioritize, and why? / What did the prototype reveal? / What remains untested? Keep the validation section explicitly marked as planned. Add real interview evidence and your personal contribution before presenting the case study as finished.' },
];
export const initialSections = [
  { id: 'overview', title: 'Project overview', label: 'The context', body: 'Smart Kitchen Companion explores how a countertop device can make everyday cooking feel more focused. The concept brings guided recipes, timers, and hands-free interaction into one experience.', status: 'Ready', asset: 'Final Render 01.png' },
  { id: 'problem', title: 'The problem', label: '01 / Understand', body: 'Cooking involves switching between recipes, timing, and preparation. This project explores how to reduce that fragmented attention without adding another complex interface to the kitchen.', status: 'Draft', asset: 'Market Research.pdf' },
  { id: 'research', title: 'From research to insight', label: '02 / Discover', body: 'Interview notes and competitor analysis informed the exploration. Add a verified interview observation here, then explain the user need and how it influenced the product direction.', status: 'Needs evidence', asset: 'User Interview.pdf' },
  { id: 'design', title: 'Exploring the solution', label: '03 / Design', body: 'Two concept directions explored the countertop form. Wireframes and a prototype developed the guided cooking flow. Explain the alternatives you considered and the reason for your final choice.', status: 'Draft', asset: 'Sketch 01.jpg' },
  { id: 'validation', title: 'Testing and learning', label: '04 / Validate', body: 'Usability testing is planned. Evaluate recipe selection, timer setup, and recovery from a missed step. Add observations and iterations after conducting the study.', status: 'Needs evidence', asset: 'Prototype.fig' },
  { id: 'reflection', title: 'Reflection and next steps', label: '05 / Reflect', body: 'The next step is to validate the interaction in a real kitchen. Document what changed your thinking, where the concept is still uncertain, and what you would explore next.', status: 'Draft', asset: 'Final Render 02.png' },
];
